# Generated by Django 3.2 on 2023-03-22 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genretitle',
            options={'verbose_name': 'Связь произведения и его жанра', 'verbose_name_plural': 'Связи произведений и их жанров'},
        ),
    ]
