# Generated by Django 3.2 on 2023-03-30 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(2023, 'Нельзя предсказывать будущие произведения')], verbose_name='Год'),
        ),
    ]
